# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=57679

// List all contributors
GET http://{{hostname}}:{{port}}/Contributors

###

// Get a specific contributor
@id_to_get=8
GET http://{{hostname}}:{{port}}/Contributors/{{id_to_get}}

###

// Add a new contributor
POST http://{{hostname}}:{{port}}/Contributors
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "phoneNumber": "1234567890"
}
